_name_or_path:
    value: unsloth/qwen2.5-3b-instruct-unsloth-bnb-4bit
_wandb:
    value:
        cli_version: 0.26.1
        e:
            iazmv6tko8c6hkfu9ay52ulc150xtk0o:
                codePath: remote/train_qlora.py
                codePathLocal: remote/train_qlora.py
                cpu_count: 2
                cpu_count_logical: 4
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "207929917440"
                        used: "48858292224"
                email: loonaticvibe2.11@gmail.com
                executable: /home/ubuntu/work/deep-learning-challenge/.venv/bin/python3
                git:
                    commit: b741ae3764b516a191d4d76b1cb2943018c3be4e
                    remote: https://x-access-token:@github.com/soma-jjya/deep-learning-challenge.git
                gpu: NVIDIA A10G
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "24146608128"
                      name: NVIDIA A10G
                      uuid: GPU-b7af6028-2776-7405-f693-c36268e84e0c
                host: ip-10-99-1-130
                memory:
                    total: "16554995712"
                os: Linux-6.8.0-1052-aws-x86_64-with-glibc2.35
                program: /home/ubuntu/work/deep-learning-challenge/remote/train_qlora.py
                python: CPython 3.11.15
                root: /home/ubuntu/work/deep-learning-challenge
                startedAt: "2026-08-05T17:57:29.920442Z"
                writerId: iazmv6tko8c6hkfu9ay52ulc150xtk0o
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.15
        t:
            "1":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 51
                - 71
                - 84
                - 95
                - 98
                - 105
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 51
                - 71
                - 84
                - 95
                - 98
                - 105
            "3":
                - 7
                - 13
                - 19
                - 62
                - 66
            "4": 3.11.15
            "5": 0.26.1
            "6": 5.14.1
            "9":
                "1": transformers_trainer
            "12": 0.26.1
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
activation_offloading:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
architectures:
    value:
        - Qwen2ForCausalLM
assistant_only_loss:
    value: false
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
batch_eval_metrics:
    value: false
bf16:
    value: true
bf16_full_eval:
    value: true
bos_token_id:
    value: null
chat_template_path:
    value: null
chunk_size_feed_forward:
    value: 0
completion_only_loss:
    value: null
data_seed:
    value: 3407
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
dataset_kwargs:
    value: null
dataset_num_proc:
    value: 8
dataset_text_field:
    value: text
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_static_graph:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
deepspeed:
    value: null
disable_tqdm:
    value: false
do_eval:
    value: false
do_predict:
    value: false
do_train:
    value: false
dtype:
    value: bfloat16
enable_jit_checkpoint:
    value: false
eos_token:
    value: <EOS_TOKEN>
eos_token_id:
    value: 151645
eval_accumulation_steps:
    value: 2
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_packing:
    value: null
eval_steps:
    value: null
eval_strategy:
    value: "no"
eval_use_gather_object:
    value: false
fp16:
    value: false
fp16_full_eval:
    value: false
fsdp:
    value: null
fsdp_config:
    value: null
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 4
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: null
hidden_act:
    value: silu
hidden_size:
    value: 2048
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_num_input_tokens_seen:
    value: "no"
initializer_range:
    value: 0.02
intermediate_size:
    value: 11008
is_encoder_decoder:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_types:
    value:
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
learning_rate:
    value: 0.0002
length_column_name:
    value: length
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: false
local_rank:
    value: -1
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: null
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: false
logging_steps:
    value: 10
logging_strategy:
    value: steps
loss_type:
    value: nll
lr_scheduler_kwargs:
    value: null
lr_scheduler_type:
    value: cosine
max_grad_norm:
    value: 1
max_length:
    value: 2048
max_position_embeddings:
    value: 32768
max_seq_length:
    value: 2048
max_steps:
    value: -1
max_window_layers:
    value: 70
metric_for_best_model:
    value: null
model/num_parameters:
    value: 3115872256
model_init_kwargs:
    value: null
model_type:
    value: qwen2
neftune_noise_alpha:
    value: null
num_attention_heads:
    value: 16
num_hidden_layers:
    value: 36
num_key_value_heads:
    value: 2
num_train_epochs:
    value: 2
optim:
    value: adamw_8bit
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: outputs/qlora
output_hidden_states:
    value: false
packing:
    value: false
packing_strategy:
    value: bfd
pad_to_multiple_of:
    value: null
pad_token:
    value: <PAD_TOKEN>
pad_token_id:
    value: 151654
padding_free:
    value: true
parallelism_config:
    value: null
peft_config:
    value:
        default:
            alora_invocation_tokens: null
            arrow_config: null
            auto_mapping:
                base_model_class: Qwen2ForCausalLM
                parent_library: transformers.models.qwen2.modeling_qwen2
                unsloth_fixed: true
            base_model_name_or_path: unsloth/qwen2.5-3b-instruct-unsloth-bnb-4bit
            bias: none
            corda_config: null
            ensure_weight_tying: false
            eva_config: null
            exclude_modules: null
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 32
            lora_bias: false
            lora_dropout: 0
            lora_ga_config: null
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save: null
            monteclora_config: null
            peft_type: LORA
            peft_version: 0.20.0
            qalora_group_size: 16
            r: 16
            revision: null
            runtime_config:
                ephemeral_gpu_offload: false
            target_modules:
                - gate_proj
                - v_proj
                - q_proj
                - o_proj
                - up_proj
                - k_proj
                - down_proj
            target_parameters: null
            task_type: CAUSAL_LM
            trainable_token_indices: null
            use_bdlora: null
            use_dora: false
            use_qalora: false
            use_rslora: false
            velora_config: null
per_device_eval_batch_size:
    value: 4
per_device_train_batch_size:
    value: 4
prediction_loss_only:
    value: false
problem_type:
    value: null
project:
    value: huggingface
push_to_hub:
    value: false
push_to_hub_token:
    value: null
quantization_config:
    value:
        bnb_4bit_compute_dtype: bfloat16
        bnb_4bit_quant_type: nf4
        bnb_4bit_use_double_quant: true
        llm_int8_enable_fp32_cpu_offload: false
        llm_int8_has_fp16_weight: false
        llm_int8_skip_modules: null
        llm_int8_threshold: 6
        load_in_4bit: true
        load_in_8bit: false
        quant_method: bitsandbytes
remove_unused_columns:
    value: false
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
rms_norm_eps:
    value: 1e-06
rope_parameters:
    value:
        rope_theta: 1e+06
        rope_type: default
run_name:
    value: qlora_r16_lr0.0002_ep2
save_on_each_node:
    value: false
save_only_model:
    value: false
save_steps:
    value: 200
save_strategy:
    value: steps
save_total_limit:
    value: 2
seed:
    value: 42
skip_memory_metrics:
    value: true
sliding_window:
    value: null
tf32:
    value: null
tie_word_embeddings:
    value: true
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: 250
trackio_bucket_id:
    value: null
trackio_space_id:
    value: null
trackio_static_space_id:
    value: null
train_sampling_strategy:
    value: random
transformers_version:
    value: 5.14.1
unsloth_fixed:
    value: true
unsloth_grpo_mini_batch:
    value: null
unsloth_logit_chunk_multiplier:
    value: null
unsloth_num_chunks:
    value: -1
unsloth_version:
    value: 2026.8.4
use_cache:
    value: false
use_cpu:
    value: false
use_liger_kernel:
    value: false
use_sliding_window:
    value: false
vllm_sampling_params:
    value: null
vocab_size:
    value: 151936
warmup_ratio:
    value: 0.03
warmup_steps:
    value: 0.03
weight_decay:
    value: 0.001
